blank_issues_enabled: false
contact_links:
  - name: General Discussion
    url: https://github.com/orgs/community/discussions
    about: For open-ended conversations that aren't bugs or feature requests.
